from PIL import ImageColor

AGENT_COLOR = ImageColor.getcolor('blue', mode='RGB')
AGENT_COLOR_BUSY = 'red'
# AGENT_NEIGHBORHOOD_COLOR = (186, 238, 247)
AGENT_NEIGHBORHOOD_COLOR = 'deepskyblue'
AGENT_OBSERVATION_COLOR = (143, 146, 146)
PREY_COLOR = '#f95d6a'

CELL_SIZE = 35